scaleway/packer-plugin-scaleway

builder/scaleway/config.go
builder/scaleway/config.hcl2spec.go
builder/scaleway/step_create_server.go
builder/scaleway/step_create_ssh_key.go
docs-partials/builder/scaleway/Config-not-required.mdx

This PR allows to create images for block volumes with a specific size.

feat: add image_size_in_gb

---

CHANGELOG.md
go.mod
go.sum

update to sdk v0.2.3

---

builder/scaleway/step_snapshot.go

Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>
A snapshot may not be available instantly, so it's better to wait before for it to be ready

add wait for snapshot

---

builder/scaleway/step_create_server.go

fix: migrate to VolumeServerTemplate

---

builder/scaleway/builder.go
builder/scaleway/config.go
builder/scaleway/config.hcl2spec.go
builder/scaleway/step_cleanup_machine_data.go
docs-partials/builder/scaleway/Config-not-required.mdx

feat/add an optionnal step to cleanup machine-specific data

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

feat: add support for devcontainer

---

builder/scaleway/artifact.go

feat: support hashicorp cloud platform

---

.github/workflows/unit-tests.yml

ci: update to go 1.20

---

builder/scaleway/step_create_server.go
builder/scaleway/step_pre_validate.go
builder/scaleway/step_pre_validate_test.go
builder/scaleway/step_server_info.go
builder/scaleway/step_shutdown.go
go.mod

chore: add scw.WithContext(ctx) in some actions

---

builder/scaleway/step_create_server.go
go.mod
go.sum

chore: bump sdk

---

.github/dependabot.yml

chore: enable dependabot for github actions

---

builder/scaleway/config.go

chore: migrate to error.As

---

version/version.go

chore: bump version for 1.1.1

---

.web-docs/components/builder/scaleway/README.md
builder/scaleway/builder_acc_test.go
builder/scaleway/config.go
builder/scaleway/config.hcl2spec.go
builder/scaleway/step_backup.go
docs-partials/builder/scaleway/Config-not-required.mdx
example/build_scaleway.pkr.hcl

feat: add support for tags

---

.github/workflows/nightly.yml
.github/workflows/unit-tests.yml

chore: fix checkout and setup-go ordering to optimize cache usage

---

.golangci.yml
builder/scaleway/artifact.go
builder/scaleway/artifact_test.go
builder/scaleway/builder.go
builder/scaleway/builder_acc_test.go
builder/scaleway/builder_test.go
builder/scaleway/config.go
builder/scaleway/step_backup.go
builder/scaleway/step_cleanup_machine_data.go
builder/scaleway/step_create_server.go
builder/scaleway/step_create_ssh_key.go
builder/scaleway/step_pre_validate.go
builder/scaleway/step_pre_validate_test.go
builder/scaleway/step_server_info.go
go.mod
main.go

chore: add linters

---

builder/scaleway/step_remove_volume.go

fix: remove_volume not working due to outdated state key

---

go.mod
go.sum

chore: bump golang.org/x/net

---

.github/CODEOWNERS

chore: add support for CODEOWNERS

---

.github/workflows/golangci-lint.yml
.golangci.yml
builder/scaleway/artifact.go
builder/scaleway/artifact_test.go
builder/scaleway/builder_test.go
builder/scaleway/step_create_ssh_key.go
internal/tester/packer_exec.go
internal/tester/tester.go

chore: migrate to golangci-lint v2
